<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_city</name>
   <tag></tag>
   <elementGuidId>4b11502c-f180-44c6-a227-3fbc69769cd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='preferredStore']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preferredStore</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preferredStore</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select Preferred State</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coral SpringsGilbertGlendaleGoodyearPhoenix (Camelback)Phoenix (Desert Ridge)ScottsdaleTempe (Emerald Center)Tempe (Tempe Marketplace)Tucson (Park Place Mall)Tucson (The Corner)BreaDaly CityElk GroveFolsomFremontFresnoHuntington BeachLaguna HillsLong BeachMountain ViewNorthridgePalm DesertPasadenaPleasant HillPleasantonRancho CucamongaRedondo BeachRosevilleSacramento (Arden)San Jose (Almaden Ranch)San MateoSan RamonTemeculaThousand OaksTustinWoodland HillsDenverManchesterMilfordNorwalkWest HartfordClaymontWilmingtonAltamonte SpringsAventuraBoca RatonBoynton BeachBrandonClearwaterDaytona BeachEsteroFort LauderdaleFort MyersGainesville (Florida)JacksonvilleKendallMelbourne (Viera)Miami (Pinecrest)Miami BeachNaplesNorth MiamiOrlando (Colonial Plaza)Orlando (Millenia Plaza)Palm Beach GardensPembroke PinesPlantationSouth SarasotaSt. PetersburgStuart (Jensen Beach)TampaUniversity Park (Sarasota)WellingtonAkers MillAlpharettaAtlantaAtlanta (Brookhaven)KennesawLexington GreenPaddock ShopsSt. MatthewsLaurel (Corridor)Towson (Beltway)BurlingtonDanversEverettNatickShrewsburyBloomingtonBurnsvilleChanhassenEaganMaple GroveMinnetonkaRoseville (Rosedale)WoodburyBrentwoodChesterfieldTown and CountryHendersonLas Vegas (Centennial)Las Vegas (Summerlin)RenoSouth StripCherry HillRiver EdgeUnionWest OrangeAlbuquerque (Cottonwood)Albuquerque (Uptown)WestburyWestburyCaryCharlotte (Myers Park)Charlotte (Promenade on Providence)Charlotte (University)ConcordDurhamGreensboro (Battleground Square)Greensboro (Oakwood Square)HuntersvilleRaleigh (Brier Creek)Raleigh (North Hills)Raleigh (Triangle Plaza)Winston-SalemCharlestonColumbiaGreenvilleKnoxvilleAllenAllianceArboretumArlingtonBaybrookCinco RanchCopperfieldDallas (Park Lane)DentonEulessFort WorthForumGalleriaHumbleLakelineLewisvilleMemorialMuellerPearlandPlano East (Collin Creek)Plano North (Preston Village)San Antonio (Del Norte)San Antonio (The Rim)Sugar LandSunset ValleyThe WoodlandsWest PlanoWest UniversityWillowbrookAlexandriaBallstonChantillyChesapeakeFairfaxFredericksburgGainesvilleLeesburgManassasMcLeanNewport News (Jefferson Commons)NorfolkRestonRichmond (Robious Hall)Richmond (Westland Plaza)Short PumpSpringfieldSterlingVirginia BeachBellevueFederal WayInterbayLynnwoodOlympiaPuyallupSeattle (Northgate)SilverdaleSpokaneSpokane ValleyTukwilaVancouverBrookfieldGreenfieldMadison</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preferredStore&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='preferredStore']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//form[@id='newuserregistration']/section[2]/div/div[3]/div[4]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[4]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
