<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_confirmationTitle</name>
   <tag></tag>
   <elementGuidId>e78c0710-7109-4d6b-8e3e-ef139cd8085b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.pagetitle>div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
